story_list = [
    "Once upon a time, a small kitten named Whiskers got lost in a big city. Whiskers wandered the streets, looking for his home. Along the way, he met many kind animals and people who tried to help him. Finally, after many adventures, Whiskers found his way back to his loving family.",
    "In a peaceful pond, a little duckling named Daisy dreamed of flying high in the sky. Despite being laughed at by other animals, Daisy practiced every day. One day, a storm threatened the pond, and Daisy's bravery and new flying skills saved all the animals. She became a hero and proved that dreams can come true with determination.",
    "In an old library, a curious child named Sam discovered a dusty, magical book. When Sam opened it, they were transported to a world full of dragons, wizards, and enchanted forests. Sam made new friends and went on exciting adventures. After learning important lessons, Sam returned home, knowing they could visit the magical world anytime by opening the book.",
    "A small robot named R1 was programmed to help humans, but R1 wanted to understand emotions. R1 set out on a journey to learn about feelings. Along the way, R1 encountered different situations that taught him about happiness, sadness, love, and friendship. In the end, R1 realized that understanding emotions made him a better helper and friend.",
    "Lila, a young girl, discovered a hidden garden in the woods behind her house. The garden was enchanted, with flowers that could talk and trees that could move. Lila spent her summer days exploring the garden and helping the magical creatures. She learned about the importance of nature and the magic of kindness.",
    "Max found an old watch in his grandfather’s attic that could travel through time. Max used the watch to visit different eras, meeting historical figures and witnessing significant events. Through his travels, Max learned valuable lessons about history and the impact of individual actions.",
    "A group of friends set sail on a boat trip and discovered a mysterious island. The island was filled with ancient ruins, hidden treasures, and strange creatures. Together, they solved puzzles and overcame challenges to uncover the island’s secrets and find their way back home, closer than ever.",
    "Ella moved into a new house and discovered it was haunted by a friendly ghost named Oliver. Oliver had been living in the house for years and was lonely. Ella and Oliver became friends, and with Ella’s help, Oliver found peace and moved on, leaving the house filled with warmth and happy memories.",
    "In the heart of a forest, a group of children found a secret treehouse that granted wishes. Each child made a wish, but they soon learned that wishes come with responsibilities. They used their wishes to help others and make the world a better place, discovering the true meaning of friendship and generosity.",
    "Captain Teddy, a brave teddy bear, protected the toys in the playroom. One day, a new toy, Princess Sparkle, was lost. Captain Teddy led a daring rescue mission through the house, facing obstacles and making new allies. Together, they brought Princess Sparkle back, and Captain Teddy’s leadership was celebrated by all the toys."
]
